"""add achievements tables

Revision ID: e60103f7d644
Revises: 0004_make_progress_validation_driven
Create Date: 2026-04-15 23:05:16.116340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60103f7d644'
down_revision = '0004_make_progress_validation_driven'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('niveles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niveles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('xp_minimo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('xp_maximo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recompensa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('xp_minimo < xp_maximo', name=op.f('ck_niveles_rango')),
    sa.PrimaryKeyConstraint('id', name=op.f('niveles_pkey'))
    )
    # ### end Alembic commands ###
